version: '3.3'

services:
    backend:
        image: example-backend
        ports: 
          - 8080:8080
        container_name: backend
        environment:
          - REDIS_HOST=redis
        
    frontend: 
        image: example-frontend
        ports: 
          - 5000:5000
        container_name: frontend

    redis:
        image: redis:7.0-bullseye
        ports:
          - 6379:6379
        volumes:
          - ./redis_volume/:/data
        container_name: redis
