version: '3.7'

services:
    backend:
      image: example-backend
      restart: unless-stopped
      ports: 
        - 8080:8080
      container_name: backend
      environment:
        - REDIS_HOST=redis
        - POSTGRES_HOST=db
      depends_on:
        - db

        
    frontend: 
      image: example-frontend
      restart: unless-stopped
      ports: 
        - 5000:5000
      container_name: frontend

    redis:
      image: redis:7.0-bullseye
      restart: unless-stopped
      ports:
        - 6379:6379
      volumes:
        - ./redis_volume/:/data
      container_name: redis

    db:
      image: postgres:alpine
      restart: unless-stopped
      container_name: db_backend
      volumes:
        - database:/var/lib/postgresql/data
      ports:
        - 5432:5432
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DATABASE=postgres

    reverse-proxy:
      image: nginx:alpine
      restart: unless-stopped
      container_name: nginx
      ports:
        - 80:80
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        
volumes:
  database:
