version: '3.3'

services:
    simple-web-service:
        image: devopsdockeruh/simple-web-service
        build: .
        container_name: simple-web-service
        command: server
        ports:
          - 8080:8080
