version: '3.3'

services:
  frontend:
    image: frontend-kurkkumopo
    build: ./ml-kurkkumopo-frontend
    ports:
      - 3000:3000
  backend:
    image: backend-kurkkumopo
    build: ./ml-kurkkumopo-backend
    ports:
      - 5000:5000
    volumes:
      - model:/src/model
  training:
    image: training-kurkkumopo
    build: ./ml-kurkkumopo-training
    volumes:
      - data:/src/data
      - model:/src/model

volumes:
  data:
  model:
